spring:
  application:
    name: shop

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopDB
    username: root
    password: root

  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true

  sql:
    init:
      mode: never

  mail:
    host: smtp.gmail.com
    port: 587
    username: jhs990313@gmail.com
    password: zqdogobomffhumms
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
            required: true

  data:
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

  web:
    resources:
      static-locations: classpath:/static/, file:/uploads/

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 213a60178962aceb34ac95e150908e3e
            client-secret: oFS9RqjEQ0XPtTPzw3jLcgeQMjItBBEt
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:3000/login/oauth2/callback/kakao
            client-authentication-method: POST
          naver:
            client-id: 1VhK6VDoVJft1ovCLs1g
            client-secret: ctjRWAelun
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:3000/login/oauth2/callback/naver
            client-authentication-method: POST
          google:
            client-id: 952861923968-h3d6tg1ojqc5mqv7d583j8aosn8ffj2p.apps.googleusercontent.com
            client-secret: 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
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:3000/login/oauth2/callback/google
            client-authentication-method: POST

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

#logging:
#  level:
#    org.hibernate: DEBUG
#    com.zaxxer.hikari: DEBUG
#    com.p6spy: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-components: always

  server:
    port: 9292

mail:
  sender:
    email: jhs990313@gmail.com

file:
  upload-dir: C://Users/JungHyunSu/react/soccershop/public/uploads

jwt:
  secret-key: u3Zs8XVDNlZ2RGF1Q0pYzJl2YXFKNENPWFZQaklxTjRaZ0NPaXpZUEtIQ3FTWnpTbGpYNW9EZEY=

app:
  redirect-uri: http://localhost:3000